/* Generated By:JJTree: Do not edit this line. PremonJJTParserTreeConstants.java */

public interface PremonJJTParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEXPTOPLEVEL = 1;
  public int JJTCATVAL = 2;
  public int JJTCATCENTRAL = 3;
  public int JJTCATPROC = 4;
  public int JJTTYPEVAR = 5;
  public int JJTTYPERESULT = 6;
  public int JJTTYPEFUNCURRIED = 7;
  public int JJTTYPETUPLE = 8;
  public int JJTTYPEDOTS = 9;
  public int JJTEXPVAR = 10;
  public int JJTEXPFUNCURRIED = 11;
  public int JJTEXPFUNTHUNK = 12;
  public int JJTEXPRETURN = 13;
  public int JJTEXPTUPLE = 14;
  public int JJTEXPDOTS = 15;
  public int JJTEXPINT = 16;
  public int JJTEXPDOUBLE = 17;
  public int JJTEXPSTRING = 18;
  public int JJTEXPAPP = 19;
  public int JJTEXPAPPINFIX = 20;
  public int JJTEXPOPTIONAL = 21;
  public int JJTEXPCOMP = 22;
  public int JJTEXPDEC = 23;
  public int JJTPATBIND = 24;
  public int JJTPATBINDFUNCURRIED = 25;
  public int JJTPATTUPLE = 26;
  public int JJTPATDOTS = 27;
  public int JJTDECCOMP = 28;
  public int JJTDECBIND = 29;
  public int JJTDECBINDFUNCURRIED = 30;
  public int JJTDECLOCALRECMANY = 31;
  public int JJTDECRECMANY = 32;
  public int JJTCONCOMP = 33;
  public int JJTCONOPTIONAL = 34;
  public int JJTCONBIND = 35;
  public int JJTCONBINDFUNCURRIED = 36;
  public int JJTID = 37;


  public String[] jjtNodeName = {
    "void",
    "ExpTopLevel",
    "CatVal",
    "CatCentral",
    "CatProc",
    "TypeVar",
    "TypeResult",
    "TypeFunCurried",
    "TypeTuple",
    "TypeDots",
    "ExpVar",
    "ExpFunCurried",
    "ExpFunThunk",
    "ExpReturn",
    "ExpTuple",
    "ExpDots",
    "ExpInt",
    "ExpDouble",
    "ExpString",
    "ExpApp",
    "ExpAppInfix",
    "ExpOptional",
    "ExpComp",
    "ExpDec",
    "PatBind",
    "PatBindFunCurried",
    "PatTuple",
    "PatDots",
    "DecComp",
    "DecBind",
    "DecBindFunCurried",
    "DecLocalRecMany",
    "DecRecMany",
    "ConComp",
    "ConOptional",
    "ConBind",
    "ConBindFunCurried",
    "Id",
  };
}
