/* Generated By:JJTree&JavaCC: Do not edit this line. PremonJJTParserConstants.java */
public interface PremonJJTParserConstants {

  int EOF = 0;
  int EQ = 7;
  int SEMI = 8;
  int COMMA = 9;
  int COLON = 10;
  int LPAREN = 11;
  int RPAREN = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int DOTS = 15;
  int FN = 16;
  int LET = 17;
  int REC = 18;
  int VAL = 19;
  int CENTRAL = 20;
  int PROC = 21;
  int LOCAL = 22;
  int RETURN = 23;
  int INT = 24;
  int DOUBLE = 25;
  int STRING = 26;
  int ID = 27;
  int ALPHANUMERIC = 28;
  int LETTER = 29;
  int DIGIT = 30;
  int SYMBOLIC = 31;
  int SYMBOL = 32;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"...\"",
    "\"fn\"",
    "\"let\"",
    "\"rec\"",
    "\"val\"",
    "\"central\"",
    "\"proc\"",
    "\"local\"",
    "\"return\"",
    "<INT>",
    "<DOUBLE>",
    "<STRING>",
    "<ID>",
    "<ALPHANUMERIC>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOLIC>",
    "<SYMBOL>",
  };

}
